<?php

namespace Nico\GooglemapsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
	public function myFindOneById($id){
		$qb = $this->createQueryBuilder('a');
		 
		$qb->leftjoin('a.markers','b')
		    ->addSelect('b')
		    ->leftjoin('b.icone','c')
		    ->addSelect('c')
		    ->where('a.id = :id')
     		->setParameter('id', $id);
		 
		    return $qb->getQuery()
		              ->getOneOrNullResult();
	}
}
