<?php

namespace Nico\GooglemapsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkerRepository extends EntityRepository
{
	
}
